add -d/--decrypt option to decrypt a file to stdout
ryantm/agenix pull request #158
Opened 2023-02-21 01:41 UTC by whentze

See https://github.com/ryantm/agenix/pull/154#issuecomment-1437566317 for some discussion.

The implementation is not super pretty, but works. Feel free to pick on the style.
I also replaced one of the `EDITOR=cat` invocations in the integration test with usage of this option.

Speaking of which, that test takes forever to run for me, it seems to wait for 5 minutes for sshd to time out. Is that expected? Maybe something related to missing entropy?

2023-02-21 02:02 UTC, ryantm commented
> Speaking of which, that test takes forever to run for me, it seems to wait for 5 minutes for sshd to time out. Is that expected? Maybe something related to missing entropy?

```
$ time nix flake check

real  0m13.916s
user  0m10.053s
sys 0m2.026s
```

2023-02-21 02:10 UTC, ryantm approved these changes
looks reasonable to me, thanks!

2023-02-21 02:21 UTC, ryantm requested changes
There is a subtle problem with this! It leaves the CLEARTEXT_DIR around after the program exits. We should fix this because it is a security issue in my opinion.

2023-02-21 02:41 UTC, n8henrie commented
@ryantm I have been wondering / worrying about this possibility (leaving behind a decrypted temp file) as complexity grows.

What would you think about adding a `trap "rm -f \"$TEMPFILE\"" EXIT` or equivalent right after the creation of the tempfile, as a little extra insurance?

2023-02-21 03:19 UTC, ryantm commented
We should add tests for it.

2023-02-21 09:13 UTC, whentze commented
Oh damn, good catch! Will fix.

2023-02-21 19:52 UTC, n8henrie commented
This PR adds a bash-style `[[` test, as opposed to the POSIX-style that has been exclusively used so far.

@ryantm Do you have a strong preference for keeping the POSIX-style? I don't imagine nix will move away from bash anytime soon, and going to the former is a little easier to use in some cases and would quiet another shellcheck warning (that I silenced in https://github.com/ryantm/agenix/pull/160, I don't think this lint is enabled by default).

2023-02-21 21:45 UTC, ryantm commented
I'm okay with using Bash style tests if needed.

2023-02-22 11:35 UTC, whentze commented
@n8henrie I didn't add the bash-style tests, only moved them around. They're already on main: https://github.com/ryantm/agenix/blob/main/pkgs/agenix.sh#L120

2023-02-22 12:37 UTC, whentze commented
> We should add tests for it.

Done, and as you said, the secret indeed stays around. Next up, I will make that test pass :)

2023-02-22 18:40 UTC, whentze commented
Done, and the test passes now.

2023-02-23 03:22 UTC, ryantm approved these changes
looks good now! I rebased it on main, squashed it down to one commit, copied the CLI help output to the readme, changed the capitalization of the help output slightly

2023-02-23 04:25 UTC, merged