doc: diff `*.age` files
ryantm/agenix pull request #177
Opened 2023-03-25 23:32 UTC by smaximov

I'd like to share the steps I used to enable cleartext Git  diffs for `*.age` files using `.gitattributes` (disclaimer: I borrowed the idea and even whole sentences from [sops](https://github.com/mozilla/sops#showing-diffs-in-cleartext-in-git)).

2023-03-25 23:50 UTC, smaximov commented
As an alternative to manually adding a helper script `rage-textconv`, maybe it's worth introducing a new option (disabled by default?) which would do it automatically? Something like this:

```nix
let ageDiffer = with pkgs; 
   writeShellApplication {
     name = "rage-textconv";
     text = ''
        ${cfg.age.ageBin} --decrypt "$1" ${
          lib.strings.concatMapStringsSep " "
          (path: "-i ${lib.strings.escapeShellArg path}")
          config.age.identityPaths
       }
    '';
  }; 
in {
  # ...

  options.age = {
    # ...
    enablePlaintextDiffer = mkOption {
      type = types.bool;
      default = false;
      # ...
    };
  };

  # ...
  config = {
    # ...
    environment.systemPackages = lib.optionals cfg.age.enablePlaintextDiffer [ ageDiffer ];
  };
}
```

But that would still require manual actions from the user.

2023-12-20 16:22 UTC, ryantm requested changes

2023-12-20 16:22 UTC, ryantm commented on README.md
> +7. (Optional) Setup git to decrypt `*.age` files when showing diffs
I don't think we should insert optional steps in the tutorial. It is hard enough to follow as is. I'd be okay with adding this as a separate section though!

2024-05-26 08:34 UTC, raboof commented
something like this would be really nice!

my ssh key has a passphrase, though, and while `git diff` does prompt for it and continues after I hit 'enter', it does not pass on all characters.

2025-08-04 15:29 UTC, closed without merging

2025-08-04 15:29 UTC, ryantm commented
closing as outdated feel free to open if you address the feedback